{- if .Values.nginx.enabled }
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: { include "myapp.fullname" . }-ingress
  annotations:
    kubernetes.io/ingress.class: nginx
spec:
  rules:
  - host: myapp.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: { include "myapp.fullname" . }
            port:
              number: { .Values.nginx.service.port }
{- end }