apiVersion: batch/v1
kind: CronJob
metadata:
  name: { include "mycronjob.fullname" . }
spec:
  schedule: "0 0 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cronjob
            image: "{ .Values.image.repository }:{ .Values.image.tag }"
            imagePullPolicy: { .Values.image.pullPolicy }
          restartPolicy: OnFailure